# Generated by Django 3.2.8 on 2021-10-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
    ]
