# Generated by Django 3.2.8 on 2021-10-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_pally_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pally',
            name='expiry_date',
        ),
    ]
