# Generated by Django 3.2.8 on 2021-10-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_auto_20211020_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pally',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pally',
            name='price_per_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_pally', to='store.price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='store.price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_product_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
