# Generated by Django 3.2.8 on 2021-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211020_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pally',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
