# Generated by Django 3.2.8 on 2021-10-20 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_alter_pally_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pally',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pally_creator', to='account.userbase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Product Discount in %'),
        ),
    ]
