# Generated by Django 3.2.8 on 2021-10-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pally',
            name='available_slots',
            field=models.IntegerField(default=0),
        ),
    ]
