# Generated by Django 3.2.8 on 2021-10-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_pally_available_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pally',
            name='available_slots',
            field=models.IntegerField(),
        ),
    ]
