# Generated by Django 3.2.8 on 2021-10-20 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_alter_pally_available_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pally',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pally_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
