# Generated by Django 3.2.8 on 2021-10-22 12:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_pally_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/basket.jfif', upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_season',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal',
            field=models.BooleanField(default=True, help_text='Does the product appear seasonal, products like meat and poultry are not seasonal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Product Discount in %'),
        ),
    ]
