# Generated by Django 3.2.8 on 2021-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20211022_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seasonal',
        ),
        migrations.AlterField(
            model_name='product',
            name='in_season',
            field=models.CharField(choices=[('In Season', 'In Season'), ('Off Season', 'Off Season'), ('Not Seasonal', '')], default='In Season', max_length=30),
        ),
    ]
