# Generated by Django 3.2.8 on 2021-10-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20211022_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_season',
        ),
    ]
