# Generated by Django 3.2.8 on 2021-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_in_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_season',
            field=models.CharField(choices=[('In Season', 'In Season'), ('Off Season', 'Off Season'), ('Not Seasonal', '')], default='In Season', max_length=30),
        ),
    ]
